// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Panamax) DeepCopyInto(out *Panamax) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Panamax.
func (in *Panamax) DeepCopy() *Panamax {
	if in == nil {
		return nil
	}
	out := new(Panamax)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Panamax) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanamaxAvailable) DeepCopyInto(out *PanamaxAvailable) {
	*out = *in
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]PanamaxAvailableVersions, len(*in))
		copy(*out, *in)
	}
	if in.Channels != nil {
		in, out := &in.Channels, &out.Channels
		*out = make([]PanamaxAvailableChannels, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanamaxAvailable.
func (in *PanamaxAvailable) DeepCopy() *PanamaxAvailable {
	if in == nil {
		return nil
	}
	out := new(PanamaxAvailable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanamaxAvailableChannels) DeepCopyInto(out *PanamaxAvailableChannels) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanamaxAvailableChannels.
func (in *PanamaxAvailableChannels) DeepCopy() *PanamaxAvailableChannels {
	if in == nil {
		return nil
	}
	out := new(PanamaxAvailableChannels)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanamaxAvailableVersions) DeepCopyInto(out *PanamaxAvailableVersions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanamaxAvailableVersions.
func (in *PanamaxAvailableVersions) DeepCopy() *PanamaxAvailableVersions {
	if in == nil {
		return nil
	}
	out := new(PanamaxAvailableVersions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanamaxCondition) DeepCopyInto(out *PanamaxCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanamaxCondition.
func (in *PanamaxCondition) DeepCopy() *PanamaxCondition {
	if in == nil {
		return nil
	}
	out := new(PanamaxCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanamaxConfig) DeepCopyInto(out *PanamaxConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanamaxConfig.
func (in *PanamaxConfig) DeepCopy() *PanamaxConfig {
	if in == nil {
		return nil
	}
	out := new(PanamaxConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PanamaxConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanamaxConfigList) DeepCopyInto(out *PanamaxConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PanamaxConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanamaxConfigList.
func (in *PanamaxConfigList) DeepCopy() *PanamaxConfigList {
	if in == nil {
		return nil
	}
	out := new(PanamaxConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PanamaxConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanamaxConfigSpec) DeepCopyInto(out *PanamaxConfigSpec) {
	*out = *in
	if in.SupportedOperandChannels != nil {
		in, out := &in.SupportedOperandChannels, &out.SupportedOperandChannels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SupportedOperandVersions != nil {
		in, out := &in.SupportedOperandVersions, &out.SupportedOperandVersions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanamaxConfigSpec.
func (in *PanamaxConfigSpec) DeepCopy() *PanamaxConfigSpec {
	if in == nil {
		return nil
	}
	out := new(PanamaxConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanamaxConfigStatus) DeepCopyInto(out *PanamaxConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanamaxConfigStatus.
func (in *PanamaxConfigStatus) DeepCopy() *PanamaxConfigStatus {
	if in == nil {
		return nil
	}
	out := new(PanamaxConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanamaxKey) DeepCopyInto(out *PanamaxKey) {
	*out = *in
	out.SecretKeyRef = in.SecretKeyRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanamaxKey.
func (in *PanamaxKey) DeepCopy() *PanamaxKey {
	if in == nil {
		return nil
	}
	out := new(PanamaxKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanamaxLicense) DeepCopyInto(out *PanamaxLicense) {
	*out = *in
	out.KeyFrom = in.KeyFrom
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanamaxLicense.
func (in *PanamaxLicense) DeepCopy() *PanamaxLicense {
	if in == nil {
		return nil
	}
	out := new(PanamaxLicense)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanamaxList) DeepCopyInto(out *PanamaxList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Panamax, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanamaxList.
func (in *PanamaxList) DeepCopy() *PanamaxList {
	if in == nil {
		return nil
	}
	out := new(PanamaxList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PanamaxList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanamaxReconciledVersions) DeepCopyInto(out *PanamaxReconciledVersions) {
	*out = *in
	in.Available.DeepCopyInto(&out.Available)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanamaxReconciledVersions.
func (in *PanamaxReconciledVersions) DeepCopy() *PanamaxReconciledVersions {
	if in == nil {
		return nil
	}
	out := new(PanamaxReconciledVersions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanamaxSpec) DeepCopyInto(out *PanamaxSpec) {
	*out = *in
	out.License = in.License
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanamaxSpec.
func (in *PanamaxSpec) DeepCopy() *PanamaxSpec {
	if in == nil {
		return nil
	}
	out := new(PanamaxSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanamaxStatus) DeepCopyInto(out *PanamaxStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]PanamaxCondition, len(*in))
		copy(*out, *in)
	}
	in.Version.DeepCopyInto(&out.Version)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanamaxStatus.
func (in *PanamaxStatus) DeepCopy() *PanamaxStatus {
	if in == nil {
		return nil
	}
	out := new(PanamaxStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}
