---
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: ibm-cpd-ae-operator
  name: ibm-cpd-ae-operator-metrics-monitor
  namespace: ibm-cpd-ae-operator-namespace
spec:
  endpoints:
    - path: /metrics
      port: https
  selector:
    matchLabels:
      control-plane: ibm-cpd-ae-operator
