resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ibm-analyticsengine-operator
  newName: icr.io/cpopen/ibm-analyticsengine-operator
  newTag: 1.0.0
