# working code
---
- hosts: localhost
  pre_tasks:
    - name: Checking for license acceptance
      include_role:
        name: common
        tasks_from: check_license.yaml
        public: no
  strategy: debug
  gather_facts: no
  roles:
    - analyticsengine
