---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibm-cpd-ae-operator-role
  labels:
    app.kubernetes.io/instance: ibm-cpd-ae-operator-role
    app.kubernetes.io/managed-by: ibm-cpd-ae-operator
    app.kubernetes.io/name: ibm-cpd-ae-operator-role
rules:
- apiGroups:
  - ""
  - batch
  - extensions
  - apps
  - policy
  - rbac.authorization.k8s.io
  - autoscaling
  - route.openshift.io
  - authorization.openshift.io
  - networking.k8s.io
  - metrics.k8s.io
  resources:
  - pods
  - pods/log
  - poddisruptionbudgets
  - secrets
  - jobs
  - configmaps
  - deployments
  - daemonsets
  - statefulsets
  - replicasets
  - services
  - services/finalizers
  - persistentvolumeclaims
  - cronjobs
  - pods/exec
  - pods/portforward
  - serviceaccounts
  - namespaces
  - roles
  - rolebindings
  - horizontalpodautoscalers
  - routes
  - routes/custom-host
  - ingresses
  - endpoints
  - cronjob
  - networkpolicies
  - events
  - jobs/status
  - pods/status
  - resourcequotas
  - resourcequotas/status
  verbs:
  - apply
  - create
  - get
  - delete
  - watch
  - update
  - edit
  - exec
  - list
  - patch
  - deletecollection
- apiGroups:
  - cpd.ibm.com
  resources:
  - cpdinstalls
  - cpdinstalls/spec
  - cpdinstalls/status
  verbs:
  - apply
  - create
  - delete
  - edit
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - build.openshift.io
  resources:
  - buildconfigs
  - buildconfigs/instantiate
  - buildconfigs/instantiatebinary
  - buildconfigs/webhooks
  - buildlogs
  - builds
  - builds/clone
  - builds/details
  - builds/log
  verbs:
  - create
  - delete
  - list
  - watch
  - get
  - patch
  - update
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams
  - imagestreams/layers
  - imagestreams/secrets
  - imagestreams/status
  - imagestreamimages
  - imagestreamimports
  - imagestreammappings
  - imagestreamtags
  verbs:
  - create
  - delete
  - list
  - watch
  - get
  - patch
  - update
- apiGroups:
  - apps
  resourceNames:
  - cpd-zen-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - apps
  resourceNames:
  - ibm-cpd-ae-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - zen.cpd.ibm.com
  resources:
  - zenservice
  - zenservices
  - zenservice/status
  - zenservices/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ae.cpd.ibm.com
  resources:
  - analyticsengine
  - analyticsengines
  - analyticsengine/status
  - analyticsengines/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certmanager.k8s.io
  resources:
  - issuers
  - issuers/status
  - issuers/finalizers
  - certificates
  - certificates/status
  - certificates/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  ##
  ## Base operator rules
  ##
#   - apiGroups:
#       - ""
#     resources:
#       - secrets
#       - pods
#       - pods/exec
#       - pods/log
#     verbs:
#       - create
#       - delete
#       - get
#       - list
#       - patch
#       - update
#       - watch
#   - apiGroups:
#       - apps
#     resources:
#       - deployments
#       - daemonsets
#       - replicasets
#       - statefulsets
#     verbs:
#       - create
#       - delete
#       - get
#       - list
#       - patch
#       - update
#       - watch
#   ##
#   ## Rules for ae.cpd.ibm.com/v1, Kind: AnalyticsEngines
#   ##
#   - apiGroups:
#       - ae.cpd.ibm.com
#     resources:
#       - analyticsengines
#       - analyticsengines/status
#       - analyticsengines/finalizers
#     verbs:
#       - create
#       - delete
#       - get
#       - list
#       - patch
#       - update
#       - watch
# # +kubebuilder:scaffold:rules
