- name: Wait until the {{ name }} nginx deployment is ready
  k8s_info:
    kind: Deployment
    name: "{{ name }}-{{ nginx.name }}"
    namespace: "{{ namespace }}"
  register: deployment_info
  retries: 10
  delay: 20
  until: deployment_info.resources[0].status.readyReplicas is defined and deployment_info.resources[0].status.availableReplicas is defined and ( deployment_info.resources[0].status.replicas == deployment_info.resources[0].status.readyReplicas ) and ( deployment_info.resources[0].status.replicas == deployment_info.resources[0].status.availableReplicas )