- name: Wait until the {{ name }} helm repo deployment is ready
  k8s_info:
    kind: Deployment
    name: "{{ name }}-helm-repo"
    namespace: "{{ namespace }}"
  register: deployment_info
  retries: 10
  delay: 20
  until: deployment_info.resources[0].status.readyReplicas is defined and deployment_info.resources[0].status.availableReplicas is defined and ( deployment_info.resources[0].status.replicas == deployment_info.resources[0].status.readyReplicas ) and ( deployment_info.resources[0].status.replicas == deployment_info.resources[0].status.availableReplicas )
 
- name: Wait until the {{ name }} deployer agent deployment is ready
  k8s_info:
    kind: Deployment
    name: "{{ name }}-deployer-agent"
    namespace: "{{ namespace }}"
  register: deployment_info
  retries: 10
  delay: 20
  until: deployment_info.resources[0].status.readyReplicas is defined and deployment_info.resources[0].status.availableReplicas is defined and ( deployment_info.resources[0].status.replicas == deployment_info.resources[0].status.readyReplicas ) and ( deployment_info.resources[0].status.replicas == deployment_info.resources[0].status.availableReplicas )

- name: Wait until the {{ name }} control plane deployment is ready
  k8s_info:
    kind: Deployment
    name: "{{ name }}-control-plane"
    namespace: "{{ namespace }}"
  register: deployment_info
  retries: 60
  delay: 30
  until: deployment_info.resources[0].status.readyReplicas is defined and deployment_info.resources[0].status.availableReplicas is defined and ( deployment_info.resources[0].status.replicas == deployment_info.resources[0].status.readyReplicas ) and ( deployment_info.resources[0].status.replicas == deployment_info.resources[0].status.availableReplicas )