---
- name: test
  k8s_info:
    api_version: v1
    kind: Secret
    name: '{{ micro_service.wdp_secret_name }}'
    namespace: '{{ namespace }}'
  register: credExistingStatus
  ignore_errors: true

- name: Generating wdp-service-id credentials
  set_fact:
   wdp_service_key : "{{ lookup('password', '/dev/null chars=ascii_lowercase,hexdigits length=13') }}"
   wdp_service_id : "icp4d-dev"
  when: credExistingStatus.resources | length == 0

- name: Create wdp-service-id credential secret
  k8s:
    state: present
    namespace: "{{ namespace }}"
    definition: "{{ lookup('template', 'create-wdp-secret.yaml.j2') | from_yaml }}"