-  name: Get the {{ name }} nginx deployment details
   k8s_info:
      kind: Deployment
      name: '{{ name }}-nginx'
      namespace: '{{ namespace }}'
   register: nginx_deployment_info
   when: is_35_upgrade
-  name: Get the {{ name }} nginx service details
   k8s_info:
      kind: Service
      name: '{{ name }}-nginx-external'
      namespace: '{{ namespace }}'
   register: nginx_service_info
   when: is_35_upgrade
-  name: Cleanup 3.5 nginx deployments
   k8s:
      state: absent
      namespace: '{{ namespace }}'
      apply: yes
      definition: '{{ lookup(''template'', item.name) | from_yaml }}'
      delete_options:
         propagationPolicy: Background
   loop:
   -  name: dataplane-nginx-deployment.yaml.j2
   -  name: dataplane-nginx-service.yaml.j2
   when: is_35_upgrade and ( nginx_deployment_info.resources[0].metadata.labels.release is defined and nginx_deployment_info.resources[0].metadata.labels.release
      == "ibm-spark-prod" ) and ( nginx_service_info.resources[0].metadata.labels.release is defined and nginx_service_info.resources[0].metadata.labels.release
      == "ibm-spark-prod" )

-  name: Create resources for {{ name }} nginx
   k8s:
      state: present
      namespace: '{{ namespace }}'
      apply: yes
      definition: '{{ lookup(''template'', item.name) | from_yaml }}'
   loop:
   -  name: dataplane-nginx-configmap.yaml.j2
   -  name: dataplane-nginx-deployment.yaml.j2
   -  name: dataplane-nginx-service.yaml.j2
   -  name: hummingbird-add-ons.yaml.j2
   -  name: hummingbird-route-configmap.yaml.j2