apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-ae-operator-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: icr.io/cpopen/ibm-cpd-analyticsengine-operator-catalog:1.0.0
  imagePullPolicy: Always
  displayName: Cloud Pak for Data IBM Analytics Engine powered by Apache Spark
  publisher: IBM
  updateStrategy:
    registryPoll:
      interval: 45m