apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    app.kubernetes.io/instance: ibm-cpd-ae-operator-subscription
    app.kubernetes.io/managed-by: ibm-cpd-ae-operator
    app.kubernetes.io/name: ibm-cpd-ae-operator-subscription
  generation: 1
  name: ibm-cpd-ae-operator-subscription
spec:
    channel: stable-v1
    installPlanApproval: Automatic
    name: analyticsengine-operator
    source: ibm-cpd-ae-operator-catalog
    sourceNamespace: openshift-marketplace
    startingCSV: ibm-cpd-ae.v1.0.1