- name: Check if {{ name }} confidential secret exists
  k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ name }}-confidential-properties"
    namespace: '{{ namespace }}'
  register: credExistingStatus
  ignore_errors: true

- name: Generating wdp-service-id credentials
  set_fact:
   confidential_properties : "{{ lookup('template', 'confidential-properties.yaml.j2') | b64encode }}"
#  when: credExistingStatus.resources | length == 0
  
- name: Create {{ name }} confidential properties secret
  k8s:
    state: present
    namespace: "{{ namespace }}"
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  loop:
    - name: create-confidential-properties-secret.yaml.j2
#  when: credExistingStatus.resources | length == 0
