apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.3.0
    operators.operatorframework.io/internal-objects: '["panamaxconfigs.sample.ibm.com"]'
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  labels:
    app.kubernetes.io/instance: sample-panamax-operator
    app.kubernetes.io/managed-by: panamax-operator
    app.kubernetes.io/name: panamax-operator
    operatorframework.io/os.linux: supported
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.ppc64le: supported
    operatorframework.io/arch.s390x: supported
  name: ibm-sample-panamax-operator.v4.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: PanamaxConfig is the Schema for the panamaxconfigs API
      displayName: Panamax Custom Implementation
      kind: PanamaxConfig
      name: panamaxconfigs.sample.ibm.com
      resources:
      - kind: PanamaxConfigs
        name: ""
        version: v1beta1
      specDescriptors:
      - displayName: Supported Operand Channels
        path: supportedOperandChannels
      - displayName: Supported Operand Versions
        path: supportedOperandVersions
      statusDescriptors:
      - displayName: Last Update
        path: lastUpdate
      version: v1beta1
    - description: Panamax is the Schema for the nginxes API
      displayName: Panamax Custom Implementation
      kind: Panamax
      name: panamaxes.sample.ibm.com
      resources:
      - kind: ConfigMaps
        name: ""
        version: v1
      - kind: Deployments
        name: ""
        version: v1
      - kind: Panamaxes
        name: ""
        version: v1beta1
      - kind: Pods
        name: ""
        version: v1
      - kind: Replicasets
        name: ""
        version: v1
      - kind: Route
        name: ""
        version: v1
      - kind: Services
        name: ""
        version: v1
      specDescriptors:
      - displayName: Operand License Structure
        path: license
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Accept Operand License
        path: license.accept
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - displayName: Key From
        path: license.keyFrom
      - displayName: Secret Key Ref
        path: license.keyFrom.secretKeyRef
      - displayName: Operand License Key
        path: license.keyFrom.secretKeyRef.name
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes:Secret
      - displayName: License
        path: license.license
      - displayName: Measure
        path: license.measure
      - displayName: Use
        path: license.use
      - displayName: Operand Running Status
        path: systemStatus
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Operand Version
        path: version
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      statusDescriptors:
      - displayName: Conditions
        path: conditions
      - displayName: Message
        path: conditions[0].message
      - displayName: Reason
        path: conditions[0].reason
      - displayName: Status
        path: conditions[0].status
      - displayName: Type
        path: conditions[0].type
      - displayName: Name
        path: name
      - displayName: Version
        path: versions
      - displayName: Available
        path: versions.available
      - displayName: Channels
        path: versions.available.channels
      - displayName: Name
        path: versions.available.channels[0].name
      - displayName: Versions
        path: versions.available.versions
      - displayName: Name
        path: versions.available.versions[0].name
      - displayName: Reconciled
        path: versions.reconciled
      version: v1beta1
    # required:
    # - description: CouchDBCluster desc via dep
    #   displayName: CouchDBCluster displayName via dep
    #   kind: CouchDBCluster
    #   name: couchdbclusters.couchdb.databases.cloud.ibm.com
    #   version: v1
  description: |
    The IBM Panamax Operator is a reference implementation operator developed by the IBM Cloud Pak Engineering squad.  For more information visit the [Github Repository](https://github.ibm.com/CloudPakOpenContent/ibm-sample-panamax-operator).
    # Name
    IBM&reg; Panamax Operator
    # Introduction
    ## Details
    The IBM&reg; Panamax Operator is the reference implementation operator produced by the Cloud Pak Engineering team.  This operator is meant to be used as a best practices and standards implementation, and will provide guidance to teams looking to design and create an operator for their offering.
    For more information and guidance refer to the following:
    * [Playbook](https://playbook.cloudpaklab.ibm.com/)
    * cloudpak-certify channel on slack
    ## Features
    *  **Panamax Operator**
      Panamax Operator is a reference implementation operator, that wraps and ngxinx operator.
    # Details
    ## Prerequisites
    An `ImageContentSourcePolicy` resource must be deployed to the cluster to mirror the images in the operator manifests to the correct location.
    ```yaml
    apiVersion: operator.openshift.io/v1alpha1
    kind: ImageContentSourcePolicy
    metadata:
      name: mirror-config
    spec:
      repositoryDigestMirrors:
      - mirrors:
        - cp.stg.icr.io/cp
        source: cp.icr.io/cp
      - mirrors:
        - cp.stg.icr.io/cp
        source: icr.io/cpopen
    ```
    Non-OLM installs:
    To install the operator through a mechanism other than OLM, the ServiceAccount that deploys the operator deployment must have RBAC access to create ClusterRole resources.
    ### Resources Required
    * Describe Minimum System Resources Required
    Minimum scheduling capacity:
    | Software  | Memory (GB) | CPU (cores) | Disk (GB) | Nodes |
    | --------- | ----------- | ----------- | --------- | ----- |
    |           |             |             |           |       |
    | **Total** |             |             |           |       |
    # Installing
    * Include installation instructions or links to documentation
    * Include the basic things necessary to install the product
    * Include environment setup or any other items required
    ## Configuration
    * Provide configuration instructions if any
    ## Storage
    * Define how storage works with the workload
    * Dynamic vs PV pre-created
    * Considerations if using hostpath, local volume, empty dir
    * Loss of data considerations
    * Any special quality of service or security needs for storage
    ## SecurityContextConstraints Requirements
    ### Panamax Controller
    The Sample Panamax Operator controller currently runs with the default Red Hat `restricted` SCC.
        This Operator also defines a custom SecurityContextConstraints object which is used to finely control the permissions/capabilities needed to deploy this Operator, the definition of this SCC is shown below:
    #### Custom SecurityContextConstraints definition:
    ```yaml
    apiVersion: security.openshift.io/v1
    kind: SecurityContextConstraints
    metadata:
      name: panamaxSCC
    allowHostPorts: false
    priority: null
    requiredDropCapabilities:
      - MKNOD
    allowPrivilegedContainer: false
    runAsUser:
      type: MustRunAsRange
    users: []
    allowHostDirVolumePlugin: false
    allowHostIPC: false
    seLinuxContext:
      type: MustRunAs
    readOnlyRootFilesystem: false
    fsGroup:
      type: MustRunAs
    groups: []
    defaultAddCapabilities: null
    supplementalGroups:
      type: RunAsAny
    volumes:
      - configMap
      - downwardAPI
      - emptyDir
      - persistentVolumeClaim
      - projected
      - secret
    allowHostPID: false
    allowHostNetwork: false
    allowPrivilegeEscalation: true
    allowedCapabilities: null
    ```
    If you wish to deploy the Operator controller under the custom SCC enforcement, then the SCC must be bound to the namespace before installing the Operator. Copy the above SCC into a file to apply it to your cluster.
    ```
    # Save the yaml definition from the README to panamax-scc.yaml
    $ oc login # login as cluster admin 
    $ oc apply -f panamax-scc.yaml
    $ oc create clusterrole panamax-scc-binding-cluster-role --verb="use" --resource="securityContextConstraints" --resource-name="panamaxSCC"
    $ oc create rolebinding panamax-scc-binding-namespace-role-binding --clusterrole="panamax-scc-binding-cluster-role" --group="system:serviceaccounts:<namespace for panamax deployment>" 
    ```
    For more information about the OpenShift Container Platform Security Context Constraints, see [Managing Security Context Constraints](https://docs.openshift.com/container-platform/4.3/authentication/managing-security-context-constraints.html).
    ## Limitations
    * Deployment limits - can you deploy more than once, can you deploy into different namespace
    * List specific limitations such as platforms, security, replica's, scaling, upgrades etc.. - noteworthy limits identified
    * List deployment limitations such as : restrictions on deploying more than once or into custom namespaces.
    * Not intended to provide chart nuances, but more a state of what is supported and not - key items in simple bullet form.
    * Does it work on ROKS? Openshift Container Platform?
    ## Documentation
    * Can have as many supporting links as necessary for this specific workload however don't overload the consumer with unnecessary information.
    * Can be links to special procedures in the knowledge center.
  displayName: Panamax Reference Sample
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - sample
  links:
  - name: Ibm Sample Panamax Operator
    url: https://ibm-sample-panamax-operator.domain
  maturity: alpha
  provider:
    name: content team
  version: 4.1.0
