- block:  
  - name: Check if 3.5 upgrade
    set_fact:
      is_35_upgrade: true
      use_force: yes
    when: >- 
      (ae_config_info is defined and ae_config_info.resources is defined 
        and ae_config_info.resources[0] is defined 
        and ae_config_info.resources[0].metadata is defined 
        and ae_config_info.resources[0].metadata.labels.icpdata_addon_version is match("3.5.*"))
  
  - name: Not a 3.5 upgrade
    set_fact:
      is_35_upgrade: false
      use_force: no
    when: is_35_upgrade is not defined
                      
  - debug:
      msg: "is_35_upgrade: {{ is_35_upgrade }}"
      
  - name: set value of use_force
    set_fact:
      use_force: yes 
    when: is_35_upgrade
  - debug:
      msg: "use_force: {{ use_force }}"
      
  - name: set merge type
    set_fact:
      ae_merge_type: json
    when: is_35_upgrade