apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: sample-panamax-operator
    app.kubernetes.io/managed-by: panamax-operator
    app.kubernetes.io/name: panamax-operator
  name: ibm-sample-panamax-operator-ibm-sample-panamax-operator
